### PR TITLE
v1.0.1

### PR DESCRIPTION
**Pull request by esenmarti**

### CODE REVIEW

**Comment by esenmarti** [comment]
I will create a new tag v1.0.1 once this PR is submitted

**Comment by nuugen** [comment]
What is this PR for?

**Comment by esenmarti** [comment]
> What is this PR for?

I prefer to tag an empty commit rather than a Renovate PR ...

**Comment by nuugen** [comment]
> I prefer to tag an empty commit rather than a Renovate PR ...

Interesting approach, I never thought about this before :)

**Review by nuugen — APPROVED** [review]

**Pull request merged**
